### ISSUE TITLE
Rename this ridiculous package to something shorter. 

### ISSUE THREAD

**Issue by NHDaly** [JuliaPerf/PerformanceProfilingHttpEndpoints.jl#14]
I like `PerfEndpoints.jl`. Some more options:
- `PerfEndpoints.jl`
- `PerfHttpEndpoints.jl`
- `ProfilingEndpoints.jl`
- `PerfServer.jl`
- `ProfilingServer.jl`

**Comment by NHDaly** [comment]
cc: @quinnj, @nickrobinson251 for input

**Comment by quinnj** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/2896623/206651732-f752ae6c-8ef8-45e2-a463-cb862572380c.png">

<img width="665" alt="image" src="https://user-images.githubusercontent.com/2896623/206651790-d1e6bdd9-05ac-4042-837c-3402a179c024.png">

**Comment by quinnj** [comment]
Thanks ChatGPT; I think my favorite suggestion is ProfileEndpoints.jl

**Comment by nickrobinson251** [comment]
- `ProfilingEndpoints.jl` i like best (less `Profile`-stdlib specifc... although right now everything _is_ from `Profile`...)
- `ProfileEndpoints.jl` i also like (and shorter / easier to spell than _Profiling_)
- `ProfilingServer.jl` would be my third choice

**Comment by NHDaly** [comment]
Cool, those are all great. I agree that ProfileEndpoints is maybe nicer than ProfilingEndpoints since it's easier to write 👍 

Let's go with that, since GPT suggested it! 😁 Can one of you make this change? I don't know if i've ever renamed a registered package before.. Is it hard?

**Comment by nickrobinson251** [comment]
it's easy; we just register it as a new package https://github.com/JuliaRegistries/General/#how-do-i-rename-an-existing-registered-package

Then users need to switch to the new (renamed) package to get any future developments

**Comment by nickrobinson251** [comment]
I don't seem to have permissions to rename the repo on GitHub -- could you do that, @NHDaly ?

Then we can register this package as usual :)

**Comment by NHDaly** [comment]
Thanks, this is now done! 👍

**Comment by nickrobinson251** [comment]
https://github.com/JuliaRegistries/General/pull/74114

**Comment by NHDaly** [comment]
Excellent. Thanks! :)

CC: @vchuravy and @ianbutterworth, since i remember you asking for this.

**Comment by IanButterworth** [comment]
Hilarious

**Comment by nickrobinson251** [comment]
Done! https://github.com/JuliaPerf/ProfileEndpoints.jl/releases/tag/v1.0.0

Users of PerformanceProfilingHttpEndpoints v0.2.10 can/should now switch to ProfileEndpoints v1.0.0. They are identical except for the name change, but only ProfileEndpoints.jl will get new releases.

e.g. Change a Project.toml with
```toml
[deps]
PerformanceProfilingHttpEndpoints = "773a18e9-432f-47dd-82a7-1a805cf6f851"

[compat]
PerformanceProfilingHttpEndpoints = "0.2"
```
to
```toml
[deps]
ProfileEndpoints = "873a18e9-432f-47dd-82a7-1a805cf6f852"

[compat]
ProfileEndpoints = "1"
```
(with the new UUID)

And likewise any `using PerformanceProfilingHttpEndpoints` -> `using ProfileEndpoints`

**Comment by NHDaly** [comment]
Thanks @nickrobinson251!

Is there any way standard to report this so that old users will see the name-change?
Like maybe make one more release under the old name that suggests to move to the new repo? Is that standard practice?

**Comment by quinnj** [comment]
> Like maybe make one more release under the old name that suggests to move to the new repo? Is that standard practice?

I've heard of people doing something like this before, with a `@warn` and `maxlog=1` in the `__init__` function.
